export const RETO_LIST_REQUEST = 'RETO_LIST_REQUEST'
export const RETO_LIST_SUCCESS = 'RETO_LIST_SUCCESS'
export const RETO_LIST_FAIL = 'RETO_LIST_FAIL'

export const RETO_DETAILS_REQUEST = 'RETO_DETAILS_REQUEST'
export const RETO_DETAILS_SUCCESS = 'RETO_DETAILS_SUCCESS'
export const RETO_DETAILS_FAIL = 'RETO_DETAILS_FAIL'

export const RETO_CREATE_REQUEST = 'RETO_CREATE_REQUEST'
export const RETO_CREATE_SUCCESS = 'RETO_CREATE_SUCCESS'
export const RETO_CREATE_FAIL = 'RETO_CREATE_FAIL'
export const RETO_CREATE_RESET = 'RETO_CREATE_RESET'

export const RETO_UPDATE_REQUEST = 'RETO_UPDATE_REQUEST'
export const RETO_UPDATE_SUCCESS = 'RETO_UPDATE_SUCCESS'
export const RETO_UPDATE_FAIL = 'RETO_UPDATE_FAIL'
export const RETO_UPDATE_RESET = 'RETO_UPDATE_RESET'