export const RETO_LIST_REQUEST = 'RETO_LIST_REQUEST'
export const RETO_LIST_SUCCESS = 'RETO_LIST_SUCCESS'
export const RETO_LIST_FAIL = 'RETO_LIST_FAIL'

export const RETO_DETAILS_REQUEST = 'RETO_DETAILS_REQUEST'
export const RETO_DETAILS_SUCCESS = 'RETO_DETAILS_SUCCESS'
export const RETO_DETAILS_FAIL = 'RETO_DETAILS_FAIL'