export const SPONSOR_ADD_ITEM = 'SPONSOR_ADD_ITEM'
export const SPONSOR_REMOVE_ITEM = 'SPONSOR_REMOVE_ITEM'
export const VISITING_SAVE_SPONSOR = 'VISITING_SAVE_SPONSOR'

export const SPONSOR_SAVE_PAYMENT_METHOD = 'SPONSOR_SAVE_PAYMENT_METHOD'

export const SPONSOR_CANTIDAD_PERSONALIZADA = 'SPONSOR_CANTIDAD_PERSONALIZADA'

